const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const sql = require('mssql');
require('dotenv').config();
const nodemailer = require('nodemailer');

const app = express();
const PORT = process.env.PORT || 8000;

// Middleware
app.use(cors());
app.use(bodyParser.json({ limit: '50mb' })); // Increased limit for file uploads (PDFs)

// Database Configuration
const dbConfig = {
    user: process.env.DB_USER || 'sa',
    password: process.env.DB_PASSWORD || 'yourStrong(!)Password',
    server: process.env.DB_SERVER || 'localhost',
    database: process.env.DB_NAME || 'EmpowerHR',
    options: {
        encrypt: true,
        trustServerCertificate: true // For local dev
    }
};

// Email Configuration
const SMTP_HOST = process.env.SMTP_HOST || 'smtp.example.com';
const SMTP_PORT = process.env.SMTP_PORT || 587;
const SMTP_USER = process.env.SMTP_USER || 'hr@empowercorp.com';
const SMTP_PASS = process.env.SMTP_PASS || 'password';

const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: SMTP_PORT,
    secure: false, // true for 465, false for other ports
    auth: {
        user: SMTP_USER,
        pass: SMTP_PASS,
    },
});

// Database Connection Pool
let pool;

const connectDb = async () => {
    try {
        pool = await sql.connect(dbConfig);
        console.log('Connected to MSSQL Database');
    } catch (err) {
        console.error('Database connection failed:', err);
        console.log('Server continuing in disconnected mode (DB calls will fail until connected)');
    }
};

connectDb();

// API Router
const apiRouter = express.Router();

// Helper for Standard CRUD Operations
const registerStandardRoutes = (route, tableName) => {
    // GET ALL
    apiRouter.get(`/${route}`, async (req, res) => {
        try {
            if (!pool) throw new Error('Database not connected');
            const result = await pool.request().query(`SELECT * FROM [${tableName}]`);
            // Basic assumption: data stored as JSON in DB is handled by frontend or specific parser if needed
            res.json(result.recordset);
        } catch (err) {
            console.error(`GET /${route} error:`, err);
            res.status(500).json({ error: err.message });
        }
    });

    // POST (Create)
    apiRouter.post(`/${route}`, async (req, res) => {
        try {
            if (!pool) throw new Error('Database not connected');
            const data = req.body;
            // Filter out 'id' if it's auto-generated by DB, BUT our frontend generates GUIDs often.
            // We'll trust the body keys match DB columns.
            const columns = Object.keys(data).join(', ');
            const paramNames = Object.keys(data).map((k, i) => `@p${i}`).join(', ');
            
            const request = pool.request();
            Object.keys(data).forEach((k, i) => {
                let val = data[k];
                if (typeof val === 'object' && val !== null) val = JSON.stringify(val);
                request.input(`p${i}`, val);
            });

            await request.query(`INSERT INTO [${tableName}] (${columns}) VALUES (${paramNames})`);
            res.json({ success: true, ...data });
        } catch (err) {
            console.error(`POST /${route} error:`, err);
            res.status(500).json({ error: err.message });
        }
    });

    // POST BULK (Create Multiple)
    apiRouter.post(`/${route}/bulk`, async (req, res) => {
        try {
            if (!pool) throw new Error('Database not connected');
            const items = req.body;
            if (!Array.isArray(items)) throw new Error('Body must be an array');

            const transaction = new sql.Transaction(pool);
            await transaction.begin();
            
            try {
                for (const data of items) {
                    const columns = Object.keys(data).join(', ');
                    const values = Object.values(data).map(val => {
                        if (val === null) return 'NULL';
                        if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
                        if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
                        return val;
                    }).join(', ');
                    
                    await new sql.Request(transaction).query(`INSERT INTO [${tableName}] (${columns}) VALUES (${values})`);
                }
                
                await transaction.commit();
                res.json({ success: true, count: items.length });
            } catch (err) {
                await transaction.rollback();
                throw err;
            }
        } catch (err) {
            console.error(`POST /${route}/bulk error:`, err);
            res.status(500).json({ error: err.message });
        }
    });

    // PUT (Update)
    apiRouter.put(`/${route}/:id`, async (req, res) => {
        try {
            if (!pool) throw new Error('Database not connected');
            const { id } = req.params;
            const data = req.body;
            
            // Exclude ID from updates
            const keysToUpdate = Object.keys(data).filter(k => k !== 'id');
            const sets = keysToUpdate.map((k, i) => `${k}=@p${i}`).join(', ');
            
            const request = pool.request();
            request.input('id', id);
            keysToUpdate.forEach((k, i) => {
                let val = data[k];
                if (typeof val === 'object' && val !== null) val = JSON.stringify(val);
                request.input(`p${i}`, val);
            });

            await request.query(`UPDATE [${tableName}] SET ${sets} WHERE id=@id`);
            res.json({ success: true });
        } catch (err) {
            console.error(`PUT /${route}/:id error:`, err);
            res.status(500).json({ error: err.message });
        }
    });

    // DELETE
    apiRouter.delete(`/${route}/:id`, async (req, res) => {
        try {
            if (!pool) throw new Error('Database not connected');
            const { id } = req.params;
            const request = pool.request();
            request.input('id', id);
            await request.query(`DELETE FROM [${tableName}] WHERE id=@id`);
            res.json({ success: true });
        } catch (err) {
            console.error(`DELETE /${route}/:id error:`, err);
            res.status(500).json({ error: err.message });
        }
    });
};

// Define Entities mapping to Routes and Tables
const entities = [
    { route: 'employees', table: 'employees' },
    { route: 'departments', table: 'departments' },
    { route: 'positions', table: 'positions' },
    { route: 'roles', table: 'roles' },
    { route: 'projects', table: 'projects' },
    { route: 'leaves', table: 'leaves' },
    { route: 'leave_types', table: 'leave_types' },
    { route: 'attendance', table: 'attendance' },
    { route: 'time_entries', table: 'time_entries' },
    { route: 'notifications', table: 'notifications' },
    { route: 'holidays', table: 'holidays' },
    { route: 'payslips', table: 'payslips' },
    { route: 'invitations', table: 'invitations' }
];

// Register Routes
entities.forEach(e => {
    registerStandardRoutes(e.route, e.table);
    console.log(`Registered routes for /api/${e.route}`);
});

// --- Custom Routes ---

// Mark Notification Read
apiRouter.put('/notifications/:id/read', async (req, res) => {
    try {
        if (!pool) throw new Error('Database not connected');
        const request = pool.request();
        request.input('id', req.params.id);
        await request.query(`UPDATE [notifications] SET [read]=1 WHERE id=@id`);
        res.json({ success: true });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Mark All Notifications Read
apiRouter.put('/notifications/read-all/:userId', async (req, res) => {
    try {
        if (!pool) throw new Error('Database not connected');
        const request = pool.request();
        request.input('userId', req.params.userId);
        await request.query(`UPDATE [notifications] SET [read]=1 WHERE userId=@userId`);
        res.json({ success: true });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Send Leave Request Notification Email
apiRouter.post('/notify/leave-request', async (req, res) => {
    try {
        const { to, cc, employeeName, employeeEmail, type, startDate, endDate, reason, isWithdrawal } = req.body;
        
        if (process.env.MOCK_EMAIL === 'true') {
            console.log(`[Mock Email] Leave Request to ${to} from ${employeeName} (${employeeEmail}): ${type}`);
            return res.json({ success: true, mock: true });
        }

        await transporter.sendMail({
            from: `"${employeeName} (via HR)" <${SMTP_USER}>`,
            to, 
            cc,
            replyTo: employeeEmail, // Reply goes to requester
            subject: `${isWithdrawal ? 'Withdrawn' : 'New'} Leave Request: ${employeeName}`,
            html: `
                <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #eee; border-radius: 5px; color: #333;">
                    <h3 style="color: #0f766e; border-bottom: 2px solid #0f766e; padding-bottom: 10px;">Leave Request ${isWithdrawal ? 'Withdrawn' : 'Submitted'}</h3>
                    <div style="margin-top: 20px;">
                        <p><strong>Employee:</strong> ${employeeName} (<a href="mailto:${employeeEmail}" style="color: #0f766e;">${employeeEmail}</a>)</p>
                        <p><strong>Leave Type:</strong> ${type}</p>
                        <p><strong>Duration:</strong> ${startDate} to ${endDate}</p>
                        <div style="background-color: #f9fafb; padding: 15px; border-radius: 5px; margin: 15px 0;">
                            <strong>Reason:</strong><br/>
                            <p style="margin: 5px 0 0 0; font-style: italic;">${reason}</p>
                        </div>
                    </div>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
                    <p style="font-size: 12px; color: #666;">
                        This email was sent via the EmpowerCorp HR Portal. 
                        <strong>Reply to this email to contact ${employeeName} directly.</strong>
                    </p>
                </div>
            `
        });
        res.json({ success: true });
    } catch (err) { 
        console.error("Email Error:", err);
        res.status(500).json({ error: err.message }); 
    }
});

// Project Assignment Notification
apiRouter.post('/notify/project-assignment', async (req, res) => {
    try {
        const { email, name, projectName, managerName } = req.body;
        
        if (process.env.MOCK_EMAIL === 'true') {
            console.log(`[Mock Email] Project Assign to ${email}: ${projectName}`);
            return res.json({ success: true, mock: true });
        }

        await transporter.sendMail({
            from: `"EmpowerCorp Projects" <${SMTP_USER}>`,
            to: email,
            subject: `New Project Assignment: ${projectName}`,
            html: `
                <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
                    <div style="background-color: #0f766e; padding: 20px; text-align: center;">
                        <h2 style="color: #ffffff; margin: 0;">Project Assignment</h2>
                    </div>
                    <div style="padding: 20px;">
                        <p>Hello <strong>${name}</strong>,</p>
                        <p>You have been officially assigned to the following project:</p>
                        <div style="background-color: #f0fdfa; border-left: 4px solid #0f766e; padding: 15px; margin: 15px 0;">
                            <h3 style="margin: 0; color: #0f766e;">${projectName}</h3>
                        </div>
                        <p><strong>Assigned by:</strong> ${managerName}</p>
                        <p>Please log in to the HR Portal to view your tasks and project timeline.</p>
                    </div>
                </div>
            `
        });
        res.json({ success: true });
    } catch (err) { 
        console.error("Email Error:", err);
        res.status(500).json({ error: err.message }); 
    }
});

// Password Reset Notification
apiRouter.post('/notify/reset-password', async (req, res) => {
    try {
        const { email } = req.body;
        
        if (process.env.MOCK_EMAIL === 'true') {
            console.log(`[Mock Email] Reset Password for ${email}`);
            return res.json({ success: true, mock: true });
        }

        await transporter.sendMail({
            from: `"EmpowerCorp Security" <${SMTP_USER}>`,
            to: email,
            subject: `Password Reset Request`,
            html: `<p>A password reset was requested for your account associated with ${email}.</p><p>If this was you, please contact IT support to proceed.</p>`
        });
        res.json({ success: true });
    } catch (err) {
        console.error("Email Error:", err);
        res.status(500).json({ error: err.message });
    }
});

// Mount API
app.use('/api', apiRouter);

// Health Check
app.get('/health', (req, res) => {
    res.json({ status: 'ok', database: pool ? 'connected' : 'disconnected' });
});

// Start Server
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});